### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by Alumopper** [F11st/NWPUInfectReport#10]
使用github action时出现错误
此前已手动填报过
```Traceback (most recent call last):
  File "/home/runner/work/NWPUInfectReport-1/NWPUInfectReport-1/xgdYqtb/infect_report.py", line 103, in get_submit_info_once
    script_text = res_tree.xpath('/html/body/script')[6].text
IndexError: list index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "./xgdYqtb/index.py", line 19, in <module>
    main()
  File "./xgdYqtb/index.py", line 11, in main
    yq.checkin()
  File "/home/runner/work/NWPUInfectReport-1/NWPUInfectReport-1/xgdYqtb/infect_report.py", line 164, in checkin
    info = self.get_submit_info_once()
  File "/home/runner/work/NWPUInfectReport-1/NWPUInfectReport-1/xgdYqtb/infect_report.py", line 160, in get_submit_info_once
    data['res'] = "获取信息失败，可能需要手动签到一次:"+e
TypeError: must be str, not IndexError
Error: Process completed with exit code 1.```

**Comment by F11st** [comment]
不是最新的

**Comment by Alumopper** [comment]
不是最新的是指——

**Comment by DJDJDJQ** [comment]
IndexError: list index out of range在上次commit解决掉了
获取信息失败应该是登录密码错误😶

**Comment by Alumopper** [comment]
好叭最后我在自己的服务器上搞定了
估摸着应该是我的环境变量设置有问题
不过在本地服务器部署的时候问题还是挺多的，如果可以的话，我想提交一个更改的readme文件说明如何在本地centos服务器部署这个项目。
